# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=URLShortner_v3
GOFILES=\
	key.go\
	main.go\
	store.go\

include $(GOROOT)/src/Make.cmd
